//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBusBookingNew.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Routing()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int RoutingID { get; set; }
        public string BusID { get; set; }
        public string StartPlace { get; set; }
        public string EndPlace { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Bus Bus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
